name = "starry-night-worker"
main = "src/index.ts"
compatibility_date = "2022-05-22"

[durable_objects]
[[durable_objects.bindings]]
# The name of the binding used to refer to the Durable Object
name = "StarryNightDurableObject"
# The exported class name of the Durable Object
class_name = "StarryNightDurableObject"
# The script where the Durable Object is defined (if it is external to this Worker)
